version: "3.3" 
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.8.0
    hostname: "filebeat.ccs.org"
    volumes:
      - type: bind
        source: ./config/filebeat.docker.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: ./config/apache.log
        target: /usr/share/filebeat
    environment:
      - LOGSTASH_HOST="http://192.168.50.112:5000"
    # disable strict permission checks
    command: ["--strict.perms=false"] 
volumes:
  filebeat:
