filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
filebeat.inputs:
- type: log
  paths: /usr/share/filebeat/apache.log
output.logstash:
   hosts: ["192.168.50.112:5000"]
